ALTER TABLE public."EXPENSE"
    ADD CONSTRAINT "FK_EXPENSE_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
        REFERENCES public."EXPENSE_CATEGORY" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX FKI_EXPENSE_EXPENSE_CATEGORY
    ON public."EXPENSE"("CATEGORY_ID");

ALTER TABLE public."EXPENSE"
    ADD CONSTRAINT "FK_USER" FOREIGN KEY ("USER_ID")
        REFERENCES public."USER" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX FKI_EXPENSE_USER
    ON public."EXPENSE"("USER_ID");

ALTER TABLE public."INCOME"
    ADD CONSTRAINT "FK_INCOME_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
        REFERENCES public."INCOME_CATEGORY" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX FKI_INCOME_INCOME_CATEGORY
    ON public."INCOME"("CATEGORY_ID");

ALTER TABLE public."INCOME"
    ADD CONSTRAINT "FK_USER" FOREIGN KEY ("USER_ID")
        REFERENCES public."USER" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;
CREATE INDEX FKI_INCOME_USER
    ON public."INCOME"("USER_ID");
